name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install Rust target
      run: rustup target add thumbv7em-none-eabihf
    - name: Make run.sh executable
      run: chmod +x run.sh
    - name: Build host components
      run: ./run.sh build-all-host
    - name: Test host components
      run: ./run.sh test-all-host
    - name: Build for target architecture
      run: ./run.sh build-target
