name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      # Space-separated list of packages that should be built and tested on the host.
      HOST_PACKAGES: "data"

    steps:
    - uses: actions/checkout@v4
    - name: Install Rust target
      run: rustup target add thumbv7em-none-eabihf
    - name: Get host target triple
      id: host
      run: echo "target=$(rustc -vV | grep 'host:' | awk '{print $2}')" >> $GITHUB_OUTPUT
    - name: Build host components
      run: |
        package_flags=$(for pkg in $HOST_PACKAGES; do echo -n "--package $pkg "; done)
        cargo build $package_flags --verbose --target ${{ steps.host.outputs.target }}
    - name: Test host components
      run: |
        package_flags=$(for pkg in $HOST_PACKAGES; do echo -n "--package $pkg "; done)
        cargo test $package_flags --verbose --target ${{ steps.host.outputs.target }}
    - name: Build for target architecture
      run: |
        exclude_flags=$(for pkg in $HOST_PACKAGES; do echo -n "--exclude $pkg "; done)
        cargo build --workspace $exclude_flags --verbose
